version: '3.8'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./tasks_value:/app/tasks
    command: celery -A parser.celery_app worker -l INFO

  celery-beats:
    restart: always
    build:
      context: .
    volumes:
      - db_value:/var/lib/postgresql/data/
    command: celery -A parser.celery_app beat -l INFO

  bot:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    restart: on-failure


volumes:
  db_value:
  tasks_value:
  postgres-data:
  redis_data:
